"""refactor_to_api_key_based

Revision ID: a7286b3d21b2
Revises: 231426f7af84
Create Date: 2025-12-03 16:28:03.573791

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7286b3d21b2'
down_revision: Union[str, None] = '231426f7af84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 清空旧数据以避免非空约束冲突
    op.execute("DELETE FROM conversations")
    op.execute("DELETE FROM usage_logs")
    
    op.add_column('conversations', sa.Column('api_key_id', sa.Integer(), nullable=False, comment='API Key ID'))
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_api_key_id'), 'conversations', ['api_key_id'], unique=False)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversations', 'user_id')
    op.add_column('usage_logs', sa.Column('api_key_id', sa.Integer(), nullable=False, comment='API Key ID'))
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.create_index(op.f('ix_usage_logs_api_key_id'), 'usage_logs', ['api_key_id'], unique=False)
    op.drop_constraint(op.f('usage_logs_user_id_fkey'), 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usage_logs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'))
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('usage_logs_user_id_fkey'), 'usage_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_usage_logs_api_key_id'), table_name='usage_logs')
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.drop_column('usage_logs', 'api_key_id')
    op.add_column('conversations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_api_key_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_column('conversations', 'api_key_id')
    # ### end Alembic commands ###